[2025-04-16T06:57:52.254+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag.py
[2025-04-16T06:57:52.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T06:57:52.303+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:57:52.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T06:57:52.374+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:57:52.356+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T06:57:52.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T06:57:52.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.332 seconds
[2025-04-16T06:58:22.726+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag.py
[2025-04-16T06:58:22.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T06:58:22.730+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:58:22.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T06:58:22.735+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:58:22.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T06:58:22.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T06:58:22.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.038 seconds
[2025-04-16T06:58:53.123+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag.py
[2025-04-16T06:58:53.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T06:58:53.133+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:58:53.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T06:58:53.147+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:58:53.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T06:58:53.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T06:58:53.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.086 seconds
[2025-04-16T06:59:23.480+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag.py
[2025-04-16T06:59:23.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T06:59:23.488+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:59:23.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T06:59:23.494+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:59:23.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T06:59:23.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T06:59:23.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-16T06:59:53.816+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag.py
[2025-04-16T06:59:53.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T06:59:53.820+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:59:53.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T06:59:53.824+0000] {logging_mixin.py:190} INFO - [2025-04-16T06:59:53.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T06:59:53.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T06:59:53.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-16T07:00:24.152+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:00:24.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:00:24.155+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:00:24.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:00:24.160+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:00:24.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:00:24.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:00:24.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-16T07:00:54.696+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:00:54.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:00:54.699+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:00:54.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:00:54.703+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:00:54.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:00:54.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:00:54.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-16T07:01:25.172+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:01:25.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:01:25.177+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:01:25.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:01:25.181+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:01:25.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:01:25.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:01:25.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-16T07:01:55.604+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:01:55.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:01:55.607+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:01:55.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:01:55.611+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:01:55.610+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:01:55.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:01:55.629+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-16T07:02:25.948+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:02:25.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:02:25.952+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:02:25.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:02:25.957+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:02:25.956+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:02:25.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:02:25.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.038 seconds
[2025-04-16T07:02:56.391+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:02:56.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:02:56.397+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:02:56.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:02:56.404+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:02:56.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:02:56.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:02:56.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.067 seconds
[2025-04-16T07:03:26.757+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:03:26.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:03:26.762+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:03:26.761+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:03:26.775+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:03:26.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:03:26.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:03:26.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.038 seconds
[2025-04-16T07:03:57.114+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:03:57.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:03:57.118+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:03:57.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:03:57.123+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:03:57.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:03:57.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:03:57.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.059 seconds
[2025-04-16T07:04:27.452+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:04:27.453+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:04:27.455+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:04:27.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:04:27.459+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:04:27.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:04:27.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:04:27.473+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.025 seconds
[2025-04-16T07:04:57.847+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:04:57.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:04:57.849+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:04:57.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:04:57.854+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:04:57.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:04:57.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:04:57.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.025 seconds
[2025-04-16T07:05:28.217+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:05:28.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:05:28.221+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:05:28.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:05:28.225+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:05:28.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:05:28.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:05:28.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-16T07:05:58.547+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:05:58.548+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:05:58.551+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:05:58.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:05:58.555+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:05:58.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:05:58.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:05:58.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-04-16T07:06:28.838+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:06:28.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:06:28.841+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:06:28.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:06:28.845+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:06:28.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:06:28.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:06:28.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-04-16T07:06:59.167+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:06:59.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:06:59.176+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:06:59.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:06:59.181+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:06:59.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:06:59.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:06:59.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2025-04-16T07:07:29.538+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:07:29.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:07:29.550+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:07:29.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:07:29.558+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:07:29.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:07:29.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:07:29.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2025-04-16T07:07:59.934+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:07:59.935+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:07:59.938+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:07:59.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:07:59.944+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:07:59.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:07:59.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:07:59.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-16T07:08:30.240+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:08:30.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:08:30.243+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:08:30.243+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:08:30.247+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:08:30.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:08:30.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:08:30.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.025 seconds
[2025-04-16T07:09:00.581+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:09:00.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:09:00.586+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:09:00.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:09:00.591+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:09:00.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:09:00.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:09:00.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.034 seconds
[2025-04-16T07:09:30.965+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:09:30.968+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:09:30.972+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:09:30.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:09:30.986+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:09:30.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:09:30.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:09:31.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.059 seconds
[2025-04-16T07:10:01.339+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:10:01.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:10:01.344+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:10:01.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:10:01.354+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:10:01.352+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:10:01.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:10:01.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2025-04-16T07:10:31.636+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:10:31.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:10:31.641+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:10:31.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:10:31.656+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:10:31.655+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:10:31.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:10:31.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-16T07:11:02.011+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:11:02.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:11:02.015+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:11:02.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:11:02.027+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:11:02.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:11:02.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:11:02.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-16T07:11:32.403+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:11:32.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:11:32.418+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:11:32.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:11:32.423+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:11:32.422+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:11:32.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:11:32.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-16T07:12:02.779+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:12:02.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:12:02.783+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:12:02.782+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:12:02.791+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:12:02.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:12:02.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:12:02.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-16T07:12:33.228+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:12:33.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:12:33.232+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:12:33.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:12:33.237+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:12:33.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:12:33.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:12:33.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-04-16T07:13:03.706+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:13:03.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:13:03.711+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:13:03.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:13:03.716+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:13:03.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:13:03.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:13:03.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-16T07:13:34.103+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:13:34.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:13:34.107+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:13:34.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:13:34.113+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:13:34.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:13:34.114+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:13:34.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-16T07:14:04.431+0000] {processor.py:186} INFO - Started process (PID=539) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:14:04.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:14:04.441+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:14:04.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:14:04.449+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:14:04.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:14:04.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:14:04.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-04-16T07:14:34.840+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:14:34.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:14:34.844+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:14:34.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:14:34.849+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:14:34.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:14:34.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:14:34.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2025-04-16T07:15:05.185+0000] {processor.py:186} INFO - Started process (PID=561) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:15:05.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:15:05.200+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:15:05.199+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:15:05.207+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:15:05.206+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:15:05.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:15:05.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2025-04-16T07:15:35.578+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:15:35.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:15:35.582+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:15:35.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:15:35.587+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:15:35.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:15:35.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:15:35.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.033 seconds
[2025-04-16T07:16:05.953+0000] {processor.py:186} INFO - Started process (PID=584) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:16:05.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:16:05.959+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:16:05.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:16:05.962+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:16:05.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:16:05.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:16:05.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.030 seconds
[2025-04-16T07:16:36.279+0000] {processor.py:186} INFO - Started process (PID=596) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:16:36.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:16:36.283+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:16:36.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:16:36.293+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:16:36.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:16:36.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:16:36.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2025-04-16T07:17:06.695+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:17:06.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:17:06.699+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:17:06.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:17:06.704+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:17:06.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:17:06.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:17:06.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-16T07:17:37.033+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:17:37.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:17:37.036+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:17:37.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:17:37.041+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:17:37.040+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:17:37.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:17:37.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.029 seconds
[2025-04-16T07:27:22.261+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:27:22.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:27:22.270+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:27:22.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:27:22.281+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:27:22.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:27:22.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:27:22.306+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.056 seconds
[2025-04-16T07:27:52.636+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:27:52.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:27:52.640+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:27:52.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:27:52.644+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:27:52.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:27:52.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:27:52.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.055 seconds
[2025-04-16T07:28:23.006+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:28:23.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:28:23.010+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:28:23.010+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:28:23.015+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:28:23.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:28:23.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:28:23.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2025-04-16T07:28:53.367+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:28:53.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:28:53.377+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:28:53.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:28:53.382+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:28:53.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:28:53.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:28:53.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-16T07:29:23.746+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:29:23.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:29:23.749+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:29:23.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:29:23.753+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:29:23.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:29:23.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:29:23.784+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-16T07:29:54.227+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:29:54.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:29:54.233+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:29:54.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:29:54.239+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:29:54.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:29:54.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:29:54.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.088 seconds
[2025-04-16T07:30:24.683+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:30:24.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:30:24.687+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:30:24.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:30:24.692+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:30:24.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:30:24.693+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:30:24.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-16T07:30:55.228+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:30:55.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:30:55.232+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:30:55.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:30:55.237+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:30:55.236+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:30:55.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:30:55.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.053 seconds
[2025-04-16T07:31:25.641+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:31:25.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:31:25.648+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:31:25.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:31:25.653+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:31:25.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:31:25.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:31:25.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-16T07:31:55.982+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:31:55.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:31:55.986+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:31:55.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:31:55.992+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:31:55.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:31:55.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:31:56.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2025-04-16T07:32:26.384+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:32:26.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:32:26.388+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:32:26.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:32:26.394+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:32:26.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:32:26.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:32:26.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-04-16T07:32:56.752+0000] {processor.py:186} INFO - Started process (PID=307) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:32:56.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:32:56.757+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:32:56.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:32:56.764+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:32:56.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:32:56.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:32:56.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2025-04-16T07:33:27.198+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:33:27.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:33:27.202+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:33:27.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:33:27.208+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:33:27.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:33:27.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:33:27.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-16T07:33:57.580+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:33:57.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:33:57.584+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:33:57.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:33:57.589+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:33:57.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:33:57.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:33:57.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2025-04-16T07:34:27.945+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:34:27.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:34:27.949+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:34:27.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:34:27.955+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:34:27.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:34:27.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:34:27.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-04-16T07:34:58.257+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:34:58.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:34:58.261+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:34:58.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:34:58.277+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:34:58.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:34:58.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:34:58.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2025-04-16T07:35:28.624+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:35:28.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:35:28.627+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:35:28.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:35:28.632+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:35:28.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:35:28.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:35:28.649+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-16T07:35:59.027+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:35:59.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:35:59.031+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:35:59.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:35:59.036+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:35:59.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:35:59.036+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:35:59.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.034 seconds
[2025-04-16T07:36:29.481+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:36:29.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:36:29.485+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:36:29.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:36:29.491+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:36:29.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:36:29.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:36:29.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-16T07:36:59.862+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:36:59.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:36:59.866+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:36:59.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:36:59.871+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:36:59.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:36:59.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:36:59.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.052 seconds
[2025-04-16T07:37:30.195+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:37:30.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:37:30.198+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:37:30.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:37:30.202+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:37:30.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:37:30.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:37:30.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-16T07:38:00.625+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:38:00.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:38:00.629+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:38:00.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:38:00.634+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:38:00.632+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:38:00.634+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:38:00.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.034 seconds
[2025-04-16T07:38:31.052+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:38:31.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:38:31.058+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:38:31.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:38:31.063+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:38:31.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:38:31.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:38:31.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2025-04-16T07:39:01.404+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:39:01.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:39:01.410+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:39:01.409+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:39:01.416+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:39:01.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:39:01.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:39:01.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-04-16T07:39:31.756+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:39:31.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:39:31.761+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:39:31.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:39:31.765+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:39:31.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:39:31.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:39:31.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-16T07:40:02.095+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:40:02.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:40:02.099+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:40:02.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:40:02.103+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:40:02.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:40:02.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:40:02.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.028 seconds
[2025-04-16T07:40:32.414+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:40:32.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:40:32.419+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:40:32.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:40:32.427+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:40:32.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:40:32.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:40:32.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2025-04-16T07:41:02.749+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:41:02.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:41:02.752+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:41:02.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:41:02.757+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:41:02.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:41:02.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:41:02.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-04-16T07:41:33.099+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:41:33.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:41:33.102+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:41:33.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:41:33.106+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:41:33.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:41:33.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:41:33.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-04-16T07:42:03.569+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:42:03.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:42:03.573+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:42:03.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:42:03.578+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:42:03.577+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:42:03.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:42:03.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.030 seconds
[2025-04-16T07:42:33.987+0000] {processor.py:186} INFO - Started process (PID=516) to work on /opt/airflow/dags/dag.py
[2025-04-16T07:42:33.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-16T07:42:33.990+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:42:33.990+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-16T07:42:33.994+0000] {logging_mixin.py:190} INFO - [2025-04-16T07:42:33.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-16T07:42:33.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-16T07:42:34.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
