[2025-04-12T00:25:03.861+0000] {processor.py:186} INFO - Started process (PID=3821) to work on /opt/airflow/dags/dag.py
[2025-04-12T00:25:03.862+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T00:25:03.863+0000] {logging_mixin.py:190} INFO - [2025-04-12T00:25:03.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T00:25:03.867+0000] {logging_mixin.py:190} INFO - [2025-04-12T00:25:03.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T00:25:03.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T00:25:03.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-04-12T00:57:24.378+0000] {processor.py:186} INFO - Started process (PID=3832) to work on /opt/airflow/dags/dag.py
[2025-04-12T00:57:24.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T00:57:24.380+0000] {logging_mixin.py:190} INFO - [2025-04-12T00:57:24.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T00:57:24.385+0000] {logging_mixin.py:190} INFO - [2025-04-12T00:57:24.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T00:57:24.385+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T00:57:24.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-12T02:10:41.417+0000] {processor.py:186} INFO - Started process (PID=3843) to work on /opt/airflow/dags/dag.py
[2025-04-12T02:10:41.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T02:10:41.422+0000] {logging_mixin.py:190} INFO - [2025-04-12T02:10:41.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T02:10:41.427+0000] {logging_mixin.py:190} INFO - [2025-04-12T02:10:41.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T02:10:41.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T02:10:41.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-12T03:29:20.482+0000] {processor.py:186} INFO - Started process (PID=3854) to work on /opt/airflow/dags/dag.py
[2025-04-12T03:29:20.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T03:29:20.484+0000] {logging_mixin.py:190} INFO - [2025-04-12T03:29:20.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T03:29:20.489+0000] {logging_mixin.py:190} INFO - [2025-04-12T03:29:20.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T03:29:20.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T03:29:20.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-12T04:49:25.724+0000] {processor.py:186} INFO - Started process (PID=3865) to work on /opt/airflow/dags/dag.py
[2025-04-12T04:49:25.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T04:49:25.733+0000] {logging_mixin.py:190} INFO - [2025-04-12T04:49:25.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T04:49:25.743+0000] {logging_mixin.py:190} INFO - [2025-04-12T04:49:25.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T04:49:25.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T04:49:25.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-12T06:12:47.203+0000] {processor.py:186} INFO - Started process (PID=3876) to work on /opt/airflow/dags/dag.py
[2025-04-12T06:12:47.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T06:12:47.205+0000] {logging_mixin.py:190} INFO - [2025-04-12T06:12:47.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T06:12:47.215+0000] {logging_mixin.py:190} INFO - [2025-04-12T06:12:47.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T06:12:47.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T06:12:47.233+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-04-12T07:18:10.355+0000] {processor.py:186} INFO - Started process (PID=3887) to work on /opt/airflow/dags/dag.py
[2025-04-12T07:18:10.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T07:18:10.358+0000] {logging_mixin.py:190} INFO - [2025-04-12T07:18:10.358+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T07:18:10.363+0000] {logging_mixin.py:190} INFO - [2025-04-12T07:18:10.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T07:18:10.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T07:18:10.380+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-12T08:04:08.439+0000] {processor.py:186} INFO - Started process (PID=3899) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:04:08.440+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:04:08.441+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:04:08.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:04:08.447+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:04:08.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:04:08.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:04:08.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-12T08:04:39.005+0000] {processor.py:186} INFO - Started process (PID=3910) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:04:39.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:04:39.008+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:04:39.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:04:39.016+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:04:39.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:04:39.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:04:39.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-12T08:05:09.457+0000] {processor.py:186} INFO - Started process (PID=3921) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:05:09.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:05:09.460+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:05:09.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:05:09.466+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:05:09.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:05:09.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:05:09.485+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-04-12T08:05:39.891+0000] {processor.py:186} INFO - Started process (PID=3932) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:05:39.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:05:39.894+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:05:39.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:05:39.899+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:05:39.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:05:39.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:05:39.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-12T08:06:10.289+0000] {processor.py:186} INFO - Started process (PID=3943) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:06:10.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:06:10.291+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:06:10.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:06:10.295+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:06:10.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:06:10.296+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:06:10.311+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.028 seconds
[2025-04-12T08:06:40.713+0000] {processor.py:186} INFO - Started process (PID=3954) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:06:40.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:06:40.716+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:06:40.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:06:40.721+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:06:40.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:06:40.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:06:40.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-04-12T08:21:49.742+0000] {processor.py:186} INFO - Started process (PID=3965) to work on /opt/airflow/dags/dag.py
[2025-04-12T08:21:49.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T08:21:49.744+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:21:49.744+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T08:21:49.749+0000] {logging_mixin.py:190} INFO - [2025-04-12T08:21:49.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T08:21:49.749+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T08:21:49.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.029 seconds
[2025-04-12T09:18:21.382+0000] {processor.py:186} INFO - Started process (PID=3976) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:18:21.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:18:21.387+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:18:21.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:18:21.393+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:18:21.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:18:21.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:18:21.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.045 seconds
[2025-04-12T09:33:15.676+0000] {processor.py:186} INFO - Started process (PID=3987) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:33:15.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:33:15.684+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:33:15.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:33:15.689+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:33:15.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:33:15.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:33:15.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-04-12T09:33:46.103+0000] {processor.py:186} INFO - Started process (PID=3998) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:33:46.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:33:46.106+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:33:46.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:33:46.112+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:33:46.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:33:46.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:33:46.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2025-04-12T09:34:16.522+0000] {processor.py:186} INFO - Started process (PID=4009) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:34:16.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:34:16.525+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:34:16.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:34:16.531+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:34:16.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:34:16.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:34:16.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-04-12T09:34:46.900+0000] {processor.py:186} INFO - Started process (PID=4020) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:34:46.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:34:46.908+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:34:46.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:34:46.914+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:34:46.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:34:46.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:34:46.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.048 seconds
[2025-04-12T09:35:17.234+0000] {processor.py:186} INFO - Started process (PID=4031) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:35:17.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:35:17.237+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:35:17.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:35:17.242+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:35:17.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:35:17.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:35:17.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2025-04-12T09:35:47.516+0000] {processor.py:186} INFO - Started process (PID=4042) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:35:47.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:35:47.520+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:35:47.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:35:47.525+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:35:47.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:35:47.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:35:47.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-12T09:36:17.873+0000] {processor.py:186} INFO - Started process (PID=4053) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:36:17.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:36:17.876+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:36:17.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:36:17.881+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:36:17.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:36:17.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:36:17.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.057 seconds
[2025-04-12T09:36:48.218+0000] {processor.py:186} INFO - Started process (PID=4064) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:36:48.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:36:48.221+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:36:48.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:36:48.226+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:36:48.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:36:48.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:36:48.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-04-12T09:37:18.631+0000] {processor.py:186} INFO - Started process (PID=4075) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:37:18.633+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:37:18.634+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:37:18.634+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:37:18.640+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:37:18.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:37:18.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:37:18.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.050 seconds
[2025-04-12T09:37:49.190+0000] {processor.py:186} INFO - Started process (PID=4086) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:37:49.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:37:49.192+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:37:49.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:37:49.198+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:37:49.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:37:49.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:37:49.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.049 seconds
[2025-04-12T09:38:19.558+0000] {processor.py:186} INFO - Started process (PID=4103) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:38:19.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:38:19.560+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:38:19.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:38:19.566+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:38:19.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:38:19.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:38:19.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-12T09:38:49.880+0000] {processor.py:186} INFO - Started process (PID=4114) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:38:49.882+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:38:49.883+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:38:49.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:38:49.891+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:38:49.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:38:49.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:38:49.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.035 seconds
[2025-04-12T09:39:20.278+0000] {processor.py:186} INFO - Started process (PID=4125) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:39:20.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:39:20.281+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:39:20.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:39:20.285+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:39:20.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:39:20.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:39:20.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-12T09:39:50.674+0000] {processor.py:186} INFO - Started process (PID=4136) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:39:50.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:39:50.680+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:39:50.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:39:50.687+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:39:50.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:39:50.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:39:50.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-12T09:40:21.047+0000] {processor.py:186} INFO - Started process (PID=4147) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:40:21.048+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:40:21.049+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:40:21.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:40:21.053+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:40:21.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:40:21.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:40:21.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.028 seconds
[2025-04-12T09:40:51.450+0000] {processor.py:186} INFO - Started process (PID=4158) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:40:51.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:40:51.453+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:40:51.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:40:51.458+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:40:51.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:40:51.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:40:51.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-12T09:41:21.836+0000] {processor.py:186} INFO - Started process (PID=4169) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:41:21.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:41:21.839+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:41:21.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:41:21.843+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:41:21.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:41:21.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:41:21.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-12T09:41:52.219+0000] {processor.py:186} INFO - Started process (PID=4180) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:41:52.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:41:52.221+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:41:52.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:41:52.225+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:41:52.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:41:52.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:41:52.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2025-04-12T09:42:22.593+0000] {processor.py:186} INFO - Started process (PID=4191) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:42:22.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:42:22.595+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:42:22.595+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:42:22.599+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:42:22.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:42:22.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:42:22.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-12T09:42:52.986+0000] {processor.py:186} INFO - Started process (PID=4202) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:42:52.987+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:42:52.988+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:42:52.988+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:42:52.992+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:42:52.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:42:52.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:42:53.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.030 seconds
[2025-04-12T09:43:23.279+0000] {processor.py:186} INFO - Started process (PID=4213) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:43:23.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:43:23.283+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:43:23.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:43:23.286+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:43:23.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:43:23.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:43:23.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-04-12T09:43:53.638+0000] {processor.py:186} INFO - Started process (PID=4224) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:43:53.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:43:53.640+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:43:53.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:43:53.644+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:43:53.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:43:53.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:43:53.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.028 seconds
[2025-04-12T09:44:24.060+0000] {processor.py:186} INFO - Started process (PID=4235) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:44:24.061+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:44:24.062+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:44:24.062+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:44:24.068+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:44:24.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:44:24.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:44:24.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2025-04-12T09:44:54.445+0000] {processor.py:186} INFO - Started process (PID=4246) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:44:54.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:44:54.451+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:44:54.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:44:54.456+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:44:54.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:44:54.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:44:54.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-04-12T09:45:24.814+0000] {processor.py:186} INFO - Started process (PID=4257) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:45:24.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:45:24.819+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:45:24.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:45:24.838+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:45:24.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:45:24.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:45:24.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-04-12T09:45:55.207+0000] {processor.py:186} INFO - Started process (PID=4268) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:45:55.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:45:55.209+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:45:55.209+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:45:55.213+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:45:55.212+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:45:55.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:45:55.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.028 seconds
[2025-04-12T09:46:25.531+0000] {processor.py:186} INFO - Started process (PID=4279) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:46:25.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:46:25.533+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:46:25.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:46:25.537+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:46:25.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:46:25.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:46:25.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-12T09:46:55.848+0000] {processor.py:186} INFO - Started process (PID=4290) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:46:55.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:46:55.851+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:46:55.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:46:55.855+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:46:55.854+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:46:55.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:46:55.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-12T09:47:26.168+0000] {processor.py:186} INFO - Started process (PID=4301) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:47:26.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:47:26.170+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:47:26.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:47:26.174+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:47:26.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:47:26.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:47:26.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-12T09:47:56.492+0000] {processor.py:186} INFO - Started process (PID=4312) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:47:56.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:47:56.497+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:47:56.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:47:56.502+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:47:56.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:47:56.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:47:56.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-04-12T09:48:27.036+0000] {processor.py:186} INFO - Started process (PID=4317) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:48:27.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:48:27.038+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:48:27.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:48:27.043+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:48:27.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:48:27.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:48:27.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.038 seconds
[2025-04-12T09:48:57.384+0000] {processor.py:186} INFO - Started process (PID=4334) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:48:57.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:48:57.388+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:48:57.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:48:57.391+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:48:57.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:48:57.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:48:57.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-04-12T09:49:27.791+0000] {processor.py:186} INFO - Started process (PID=4345) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:49:27.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:49:27.794+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:49:27.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:49:27.798+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:49:27.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:49:27.799+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:49:27.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-12T09:49:58.116+0000] {processor.py:186} INFO - Started process (PID=4356) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:49:58.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:49:58.119+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:49:58.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:49:58.123+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:49:58.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 12
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:49:58.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:49:58.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-04-12T09:49:59.138+0000] {processor.py:186} INFO - Started process (PID=4361) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:49:59.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:49:59.139+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:49:59.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:49:59.143+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:49:59.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:49:59.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:49:59.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.017 seconds
[2025-04-12T09:50:29.548+0000] {processor.py:186} INFO - Started process (PID=4372) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:50:29.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:50:29.550+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:50:29.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:50:29.555+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:50:29.554+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:50:29.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:50:29.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.030 seconds
[2025-04-12T09:50:59.832+0000] {processor.py:186} INFO - Started process (PID=4383) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:50:59.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:50:59.834+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:50:59.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:50:59.837+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:50:59.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:50:59.838+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:50:59.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.024 seconds
[2025-04-12T09:51:30.131+0000] {processor.py:186} INFO - Started process (PID=4394) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:51:30.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:51:30.134+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:51:30.133+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:51:30.139+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:51:30.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:51:30.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:51:30.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-12T09:55:12.693+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:55:12.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:55:12.695+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:55:12.695+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:55:12.699+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:55:12.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:55:12.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:55:12.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.022 seconds
[2025-04-12T09:55:43.029+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:55:43.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:55:43.033+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:55:43.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:55:43.038+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:55:43.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:55:43.039+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:55:43.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.035 seconds
[2025-04-12T09:56:13.409+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:56:13.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:56:13.413+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:56:13.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:56:13.419+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:56:13.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:56:13.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:56:13.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.035 seconds
[2025-04-12T09:56:43.784+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:56:43.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:56:43.789+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:56:43.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:56:43.795+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:56:43.793+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:56:43.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:56:43.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-12T09:57:14.230+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:57:14.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:57:14.235+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:57:14.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:57:14.240+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:57:14.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:57:14.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:57:14.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-12T09:57:44.621+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:57:44.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:57:44.624+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:57:44.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:57:44.629+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:57:44.628+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:57:44.629+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:57:44.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-04-12T09:58:14.978+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:58:14.980+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:58:14.982+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:58:14.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:58:14.987+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:58:14.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:58:14.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:58:15.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.036 seconds
[2025-04-12T09:58:45.264+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:58:45.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:58:45.268+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:58:45.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:58:45.271+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:58:45.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:58:45.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:58:45.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-04-12T09:59:15.659+0000] {processor.py:186} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:59:15.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:59:15.663+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:59:15.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:59:15.667+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:59:15.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:59:15.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:59:15.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.054 seconds
[2025-04-12T09:59:46.101+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag.py
[2025-04-12T09:59:46.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T09:59:46.107+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:59:46.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T09:59:46.111+0000] {logging_mixin.py:190} INFO - [2025-04-12T09:59:46.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T09:59:46.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T09:59:46.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-12T10:00:16.518+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/dag.py
[2025-04-12T10:00:16.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T10:00:16.523+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:00:16.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T10:00:16.528+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:00:16.527+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T10:00:16.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T10:00:16.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2025-04-12T10:00:46.893+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag.py
[2025-04-12T10:00:46.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T10:00:46.903+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:00:46.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T10:00:46.913+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:00:46.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T10:00:46.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T10:00:46.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-12T10:01:17.356+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag.py
[2025-04-12T10:01:17.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T10:01:17.360+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:01:17.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T10:01:17.365+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:01:17.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 14
    folder_path = "https://raw.githubusercontent.com/btphan95/greenr-airflow/master/data/dandelion/"00000000.jpg"
                                                                                                             ^
SyntaxError: invalid imaginary literal
[2025-04-12T10:01:17.365+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T10:01:17.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.035 seconds
[2025-04-12T10:01:24.511+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/dag.py
[2025-04-12T10:01:24.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T10:01:24.514+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:01:24.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T10:01:24.520+0000] {logging_mixin.py:190} INFO - [2025-04-12T10:01:24.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T10:01:24.520+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T10:01:24.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.035 seconds
[2025-04-12T11:09:38.254+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:09:38.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:09:38.256+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:09:38.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:09:38.266+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:09:38.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:09:38.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:09:38.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2025-04-12T11:10:08.605+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:10:08.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:10:08.609+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:10:08.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:10:08.613+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:10:08.612+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:10:08.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:10:08.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.027 seconds
[2025-04-12T11:10:38.950+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:10:38.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:10:38.961+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:10:38.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:10:38.967+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:10:38.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:10:38.968+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:10:38.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.058 seconds
[2025-04-12T11:11:09.296+0000] {processor.py:186} INFO - Started process (PID=219) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:11:09.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:11:09.307+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:11:09.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:11:09.324+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:11:09.323+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:11:09.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:11:09.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2025-04-12T11:11:39.664+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:11:39.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:11:39.668+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:11:39.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:11:39.673+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:11:39.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:11:39.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:11:39.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.042 seconds
[2025-04-12T11:12:10.035+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:12:10.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:12:10.038+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:12:10.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:12:10.054+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:12:10.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:12:10.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:12:10.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2025-04-12T11:12:54.455+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:12:54.456+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:12:54.459+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:12:54.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:12:54.464+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:12:54.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:12:54.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:12:54.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.031 seconds
[2025-04-12T11:13:24.775+0000] {processor.py:186} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:13:24.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:13:24.779+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:13:24.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:13:24.784+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:13:24.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:13:24.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:13:24.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.038 seconds
[2025-04-12T11:13:55.098+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:13:55.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:13:55.102+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:13:55.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:13:55.117+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:13:55.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:13:55.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:13:55.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.047 seconds
[2025-04-12T11:14:25.449+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:14:25.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:14:25.452+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:14:25.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:14:25.455+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:14:25.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:14:25.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:14:25.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.026 seconds
[2025-04-12T11:14:56.011+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:14:56.011+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:14:56.015+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:14:56.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:14:56.023+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:14:56.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:14:56.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:14:56.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.038 seconds
[2025-04-12T11:39:08.670+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:39:08.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:39:08.673+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:39:08.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:39:08.677+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:39:08.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:39:08.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:39:08.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2025-04-12T11:39:39.493+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:39:39.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:39:39.497+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:39:39.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:39:39.502+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:39:39.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:39:39.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:39:39.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.039 seconds
[2025-04-12T11:40:09.688+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:40:09.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:40:09.691+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:40:09.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:40:09.695+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:40:09.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:40:09.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:40:09.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.024 seconds
[2025-04-12T11:40:40.162+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:40:40.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:40:40.166+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:40:40.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:40:40.172+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:40:40.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:40:40.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:40:40.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
[2025-04-12T11:41:10.968+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/dag.py
[2025-04-12T11:41:10.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-12T11:41:10.974+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:41:10.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-12T11:41:10.980+0000] {logging_mixin.py:190} INFO - [2025-04-12T11:41:10.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-12T11:41:10.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-12T11:41:11.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.043 seconds
